### ISSUE TITLE
Did you use gaia like  Xor drive? Would be the data of users stored in mongodb?

### ISSUE THREAD

**Issue by gitkiwikiwi** [hKedia/dShare-blockstack#1]
I usually use xor drive, and it can stores data of users to gaiahub to secure the privacy?But ,I notice that I have to install mongodb locally, for this app, would be the data of users stored in mongodb or gaiahub?

**Comment by hKedia** [comment]
MongoDB is used for the radiks server. All the data is stored on gaiahub.
To learn how radiks work check: https://github.com/blockstack-radiks/radiks

**Comment by hKedia** [comment]
I have updated the docs to better explain how MongoDB is used. Thanks.
